### PR TITLE
Add support for roles.

### PR DESCRIPTION
**Pull request by metmajer**
Hi @wizwjw! The following PR adds support for Tomcat roles.

### CODE REVIEW

**Comment by m11y** [comment]
Great work!

**Comment by metmajer** [comment]
Actually, it's been a one-liner, a really helpful one though ;-)

**Comment by metmajer** [comment]
Can you push it to Ansible Galaxy?

**Comment by m11y** [comment]
I'm already do Re-import in Ansible Galaxy,  but after three hours, it still in `Import task pending`, may be there is something wrong with it. I will do it again this afternoon.

**Comment by m11y** [comment]
@metmajer done.

**Pull request merged**
